ignoreScripts: true
minimumReleaseAge: 2880
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3'
  - 'semver@6.3.1'
nodeLinker: hoisted
# always use installed version of pnpm (rather than whatever is specified in package.json) and output log message so we know
pmOnFail: warn
cacheDir: ./.pnpm-cache
storeDir: ./.pnpm-store
